Repository pluginsGLPI/escalade, pull requests merged in 2025-03, with the labels that each got.

#296 Chore(i18n): update translations
  locales/cs_CZ.po
  locales/en_GB.mo
  locales/en_GB.po
  locales/es_AR.po
  locales/es_EC.po
  locales/escalade.pot
  locales/fr_CA.po
  locales/fr_FR.po
  locales/hr_HR.po
  locales/it_IT.po
  locales/ko_KR.po
  locales/pt_BR.po
  locales/ru_RU.po
  locales/sk_SK.po
  locales/tr_TR.mo
  locales/tr_TR.po
Labels: i18n

#298 Chore(i18n): update translations
  locales/cs_CZ.po
  locales/en_GB.mo
  locales/en_GB.po
  locales/es_AR.po
  locales/es_EC.po
  locales/escalade.pot
  locales/fr_CA.po
  locales/fr_FR.po
  locales/hr_HR.po
  locales/it_IT.po
  locales/ko_KR.po
  locales/pt_BR.po
  locales/ru_RU.po
  locales/sk_SK.po
  locales/tr_TR.mo
  locales/tr_TR.po
Labels: i18n

#299 Chore(i18n): update translations
  locales/cs_CZ.po
  locales/en_GB.mo
  locales/en_GB.po
  locales/es_AR.po
  locales/es_EC.po
  locales/escalade.pot
  locales/fr_CA.po
  locales/fr_FR.po
  locales/hr_HR.po
  locales/it_IT.po
  locales/ko_KR.po
  locales/pt_BR.po
  locales/ru_RU.po
  locales/sk_SK.po
  locales/tr_TR.mo
  locales/tr_TR.po
Labels: i18n

#310 Fix(Core): prevent undefined index on climb
  CHANGELOG.md
  inc/ticket.class.php
Labels: bug

#317 fix(group): user was deleted during ticket creation with use_assign_user_group enabled
  hook.php
  inc/ticket.class.php
  tests/units/GroupEscalationTest.php
Labels: Need unit tests
